todo_task:
  description: >
    Today is {weekday} in week {week} and it is morning.

    We are packing Alvildes bag and bike, so help us with a checklist!

    Gather info on any homework or things to bring to school as well as
    any things Alvilde should bring for sports later in the day.

    Also - always pack these:
     - [ ] lunch
     - [ ] charged clock
     - [ ] keys
     - [ ] bicycle helmet

  expected_output: >
    A to-do list of everything Alvilde needs to pack, before leavning the house
    on {weekday} morning including any homework in the weekly schedule.
    
    And write the list in danish and as a markdown checklist (using ' - [ ] ....')!

    Under the checklist - add the text for that day in the schedule (verbatim!)
    E.g. under the to-do list for monday, add the original text for monday in the supplied schedule.
    Make sure to put the original text in a markdown <details>

    Some books might be called the same in different classes, so remember to make it clear
    which class a book is for. For example: instead of grundbog, write grundbog i matematik (if for math class of course)
    but if the schedule says to bring "The Bible" for religion, then that is of course specific enough :)

    Do not add a title above the to-do list. Here is a good example:
    ------ EXAMPLE START ------
    - [ ] Madpakke
    - [ ] Opladet ur
    - [ ] N칮gler
    - [ ] Cykelhjelm
    - [ ] Mat. Opgavebog
    - [ ] Dansk arbejdsbog

    <details>
    ### Fredag
    ### Matematik
    **Lektie** : Opgavebogen s. 38-40

    Lektien bliver gennemg친et og vi taler i klassen om forskellige divisionsmetoder. 游땏

    Vi g친r ud i skoleg친rden, hvor vi skal lave et l칮b. Her skal eleverne indsamle information, som de skal bruge til at lave divisionsstykker med. 游땏

    ### Dansk
    3. lektion: 

    - Vi l칝ser teksten "Tyrannosofaen " af Trond E. Haugan p친 s. 96 i **Fandango** og starter med opgaverne dertil i arbejdsbogen.'
    </details>
    ------ EXAMPLE END ------

    Finally save the checklist as a markdown file named week-{week}-{weekday}.md

  agent: schedule_reader
